# Generated by Django 5.2.9 on 2026-07-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
